inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: '3.1'
  Exclude:
    - .git/**/*
    - tmp/**/*
    - vendor/**/*
    - suo.gemspec

Lint/DuplicateMethods:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/NonNilCheck:
  Enabled: true

Style/Not:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/Alias:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Style/AndOr:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 128

Metrics/MethodLength:
  Max: 32

Metrics/PerceivedComplexity:
  Max: 8

# Disabled

Style/EvenOdd:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false
